### ISSUE TITLE
Limit order issue

### ISSUE THREAD

**Issue by taroutson2002** [hughestu/MATLAB-Binance-API#14]
I am facing error code -1111: "Precision is over the maximum defined for this asset", while having no issue with market orders. Worth to mention that I am using the round command and tried to set up the  decimals at  8 and less than 8, however, still gettin the same error

**Comment by hughestu** [comment]
Can you provide code for me to replicate this? Also check pub.exchangeInfo for the precision.

**Comment by taroutson2002** [comment]
Here is the code

Symbol = 'shibusdt';
Current_Price = pub.price(Symbol);
Order_Price =round(str2double(Current_Price.price),8);
balance=600;
quanti=round((balance/Order_Price),-1);
obj = spot.newOrder('limit');
set(obj,'symb',Symbol,'side','buy','quantity',quanti,'price',Order_Price)
s = obj.send

**Comment by hughestu** [comment]
I've made some changes to fix this, and the example you provided will work fine now. I've tested numerous other cases too. Previously, I used a blanket eight-digit precision when formatting prices and quantities into the query strings. That was fine because trading precisions (as far as I recall) were all eight, but that is no longer the case. The latest version of this repository now formats price and quantity values into the query strings with a precision that is the same as the user-defined values up to a maximum of 8 digits precision.
